spring:
  datasource:
    url: ${DB_URL}     # p.ej: jdbc:mysql://host:3306/data_collector?useSSL=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false

  flyway:
    # Si algún día te conectas a una DB ya existente sin metadata de Flyway:
    baseline-on-migrate: ${FLYWAY_BASELINE:false}

